### ISSUE TITLE
Use hpack by default

### ISSUE THREAD

**Issue by andorp** [liqd/aula#143]
Add `aula.cabal` to `.gitignore` and generate the cabal file during the build process on travis.

**Comment by Mikolaj** [comment]
If so, we also need to update README.md.

**Comment by fisx** [comment]
@np argued that it's better to have aula.cabal under git control for everybody who has no hpack installed.  I can live with the noise in the commits, since we know that we can ignore all changes in aula.cabal and just need to look at package.yaml.

I will close this for now; feel free to re-open if you want to discuss more.
