### ISSUE TITLE
`garbitrary` does not support recursive ADTs.

### ISSUE THREAD

**Issue by fisx** [liqd/aula#163]
In #149, we introduced `Arbitrary` instances based on `garbitrary`.  However, documentation of `Generics.SOP.Arbitrary` in `basic-sop-0.2.0.0` says:

```haskell
-- Note that currently no attempts are being made to generate arbitrary
-- values of a particular size, and it is possible that this function
-- diverges for recursive structures.
```

We worked around this in #161 by scaling down the size parameter everywhere until `RenderHtml` terminated again, at the cost of having empty values most of the time.

A better solution would be a PR that handles recursive ADT properly, and revert the extra down-scaling.

**Comment by kosmikus** [comment]
It's unfortunately not trivial to come up with a generic definition of arbitrary that implements scaling well, because the notion of size is very different depending on actual datatypes involved. The only approach I can think of that is reasonably straight-forward is to simply divide the size evenly over all the components in a product. I'm afraid that in practice, this will still lead to much "smaller" values than you'd typically expect.

**Comment by fisx** [comment]
ah, good to know.  but wouldn't that still be an improvement over infinite values?
