### ISSUE TITLE
sending email

### ISSUE THREAD

**Issue by fisx** [liqd/aula#212]
I think we can use thentos for this, too.

Emails need to be send to the idea space moderator for every page that reaches a quorum.  But it would also be ok to resolve this issue for now by adding some test page that sends a one-line email on button push.

**Comment by np** [comment]
We should have a look at mailgun.com:

* Easier to administrate, just a REST API with an auth token.
* Cheap: free as long as we send <10000 mails per month
* Send from any domain we own: just need to setup DNS records (spf) to tell that this ok for them to send emails on our behalf.
* Package(s) available on Hackage.

**Comment by fisx** [comment]
@rittermo we need a decision from you.  mailgun cloud or liqd's smtp?

My two cents:

- we already have set up mail service at liqd and it's working reasonably well.
- mailgun may cause us fewer spam gray-listing headaches or more, hard to tell.  if i had to bet, i'd probably put my money on mailgun.
- connecting aula to mailgun is a similar effort as connecting to our own mail service.
- privacy of unencrypted emails is not that great, but we would probably have to get the ok from our users before we go ahead and send *everything* through a cloud service.
- 10k email per month is probably not enough.  that's about one email per user per month, or less.  so there is money involved.

**Comment by rittermo** [comment]
Hey @slomo, could you give us some input here? What experience do we have from other projects? Was our Liquid mailserver ever a problem? Did we evaluate using mailgun before? Thanks for your help!

**Comment by slomo** [comment]
Since it was important for to not use external services we didn't evaluate any external services so far. Of course one has always issues when sending mass mail, but there where no major issues in the past months. To be honest we don't check it that much. But I can't remember any user complain and I am also receiving all the bounces messages and take a brief look into most of them. 

If you want statistics or rest api our mail servers can't offer this.

**Comment by rittermo** [comment]
We should use the Liquid mailservers, then, because

a) we don’t want to rely too much on third party services
b) we care about keeping the data as much as possible close to us
c) no one would be willing to pay the fee if we reach more than 10.000 emails/month

I would re-consider once we think about sending out newsletters or other batch emails, but that is currently not a requirement.

**Comment by fisx** [comment]
thanks moritz.  i'll re-open this, though, since we still need to implement this feature.  (-:

**Comment by fisx** [comment]
(also thanks yves!)
