### ISSUE TITLE
Terminate JuryPhase

### ISSUE THREAD

**Issue by fisx** [liqd/aula#305]
If the principal refuses to decide on an idea in a topic, the topic will remain in `JuryPhase` indefinitely.  It would be better to have a time trigger, and an idea result that sais "has not been touched by the dean".

If the principal behaves according to protocol, this will not change anything.  If she doesn't, it will make sure that topics are not blocked indefinitely, and it can (does not have to) be made explicit that she has failed to do her job.

This requires extra emails ("topic X requires your attention, you have Y days left!"), a composite trigger triggered by timeout *or* an "all ideas have been processed" event, and a lot of phase handling machinery that we need elsewhere as well.  The extra cost for this feature should be minimal.

**Comment by rittermo** [comment]
@fisx I see your point, but I would not like to implement this at this time. If a topic rests in the JuryPhase for a very long time, it could be due to a number of reasons and the school – especially the students – should deal with it offline for the time being. Once AuLa is productively used, we can still observe if this is such a pressing issue that it must be fixed/enforced in the software.

**Comment by fisx** [comment]
ok, thanks!
