### ISSUE TITLE
restrict moderators to certain idea spaces?

### ISSUE THREAD

**Issue by fisx** [liqd/aula#314]
i think what we want is a way to express that moderator A is involved with idea spaces X, Y, Z, and *only* with those.

otherwise, every moderator would be emailed about every idea (in any idea space) that reaches a quorum.

technicalities: one way of implementing this is to give the Moderator role a 'school class' parameter, like with student.  this would mean that we need to allow for one user to have multiple roles, which we will want to for other things sooner or later.  there may be other ways to implement this.

**Comment by fisx** [comment]
@rittermo: you can choose to close this and we will stick with the current plan.  i don't expect this to be more expensive to fix later, when the issue becomes appearent.

**Comment by rittermo** [comment]
Moderators should be able to see all classes, so we should stick to our plan. I think this is due to the fact that in some schools there will be school-wide moderators only. It would be nice if notification emails could include the class in the subject line, so moderators can use mail filters. I’ll update that requirement as a NTH in the phase user stories’ acceptance criteria.
