### ISSUE TITLE
 Refactor saveAndEnactFreeze

### ISSUE THREAD

**Issue by fisx** [liqd/aula#496]
This has been done in 90272b4 in #491, but I'm not convinced that the `assert` is really not necessary.  Therefore, the PR has this commit reverted.

We should add a quickcheck property that replaces it, then cherry-pick this commit and use it in the production .code.  It's much nicer!

**Comment by fisx** [comment]
[irc]

```
17:11 < npou> I don't see the benefit of keeping the assertion but that's your call. To me the 
              assertion was needed because we couldn't deal with the resulting actions, and the 
              assertion can morally stay in the phaseTrans function
```

**Comment by Mikolaj** [comment]
I agree with @np that the assertion is not needed in the new version of the code. That's because the new version doesn't use `phaseTrans` and so, even if `phaseTrans` is (wrongly) changed as indicated by @np in the comment, nothing wrong can happen. 

OTOH, I think not using `phaseTrans` in the new version is misleading, because morally we do want to make a phase transition. It just happens that in the current arch we can't (easily) handle the side-effects (the actions). The use of `phaseTrans` and the assertion conveys just that. If `phaseTrans` really creates some actions here in the future (very unlikely), we will probably change the code to execute them, not silently ignore them as in the new version of the code.

**Comment by fisx** [comment]
thanks @Miklaj, that's exactly what was bugging me, but i couldn't put my finger on it.  so i suggest we un-revert the two offending commits and instead crash in the resp. `phaseTrans` cases.  this way should we ever want to add actions in the future, we'll see what we have to do for it to work.

**Comment by fisx** [comment]
(@np: another very small thing.  if you want something more interesting to do, just assign to me and i'll do it.)
