### ISSUE TITLE
Better UX for progress bar in voting phase

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#506]
The progress bar on the idea detail page in the voting phase currently shows red (no votes), green (yes votes) and yellow (implicit abstains = number of students in idea space). This seems to be confusing not just to me but also to Marina‘s sister. I would suggest two changes: 

1. Do not show the implicit abstains, i.e. the yellow part of the bar
1. If no votes were cast the bar is just and shows the “0 votes"

(v0.11.3)

---
Original text from the client: 

Unter besagter Leiste werden Stimmen dafür und dagegen richtig angezeigt, unter dem gelben Teil der Leiste steht allerdings völlig unabhängig von der Anzahl der gegebenen Stimmen immer die Nummer 20.

**Comment by fisx** [comment]
the german text from the feedback to me means that the number under the "not voted" count is wrong: no matter how may people didn't vote, the number shown is always 20.

so i still want to leave this as is (except perhaps for the colour), and just fix the wrong number (probably a left-over dummy value that needs to be calcludated, it's a small change).

NOTE: I distinguish "abstained" (cast an explicit neutral vote) from "not voted" (e.g., because off-line during the entire voting phase).  we don't have "abstained", but we certainly have "not voted", and i think it's relevant information and it should be shown.

**Comment by rittermo** [comment]
a) The number of not voted  showed 130 for me, so I guess it depends on how many users are created? Not sure if it is wrong

b) I think it is confusing the way it is shown right now. I agree though, that the information is valuable. Maybe on the idea detail page we could add a line of text underneath saying “x number of eligible users have voted” to make it more clear and not just show a yellow bar out of the blue (excuse the pun)?

**Comment by fisx** [comment]
@rittermo let's fight this out off-line?  might be easier.  (-:

**Comment by fisx** [comment]
I think I closed this implicitly by accident.  Re-opening until we've got more client feedback.

See also:
- https://github.com/liqd/aula/pull/524#issuecomment-220771479
- https://github.com/liqd/aula/pull/524#issuecomment-220772366

**Comment by fisx** [comment]
discussion with @rittermo: a consensus has evolved that the yellow part of the vote bar is an improvement over the original design.  so this is resolved.
