### ISSUE TITLE
Show progress bar in list view

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#507]
The progress bar should indicate yes and no votes in the list view of a topic in the voting phase (topic overview). Currently in v0.11.3 only a grey bar is shown like here: https://thentos-dev-frontend1.liqd.net/space/school/topic/149/ideas

---
Original text from the client: 
In der Liste der Ideen im Thema, wo die Anzahl der Stimmen für jede Idee angezeigt wird, werden nur Stimmen dafür gezählt, Stimmen dagegen nicht angezeigt. Darunter steht die selbe grün-und-graue Leiste, die in der Wilde-Ideen-Phase verwendet wird, wo die dreifarbige Leiste, die auf der Seite der Idee selbst verwendet wird, wohl übersichtlicher und informativer wäre.

**Comment by fisx** [comment]
Adding a screen shot in case the staging server moves:

![2016-05-18-114652_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/15354502/3f436b88-1cee-11e6-8378-672ee95f8609.png)

**Comment by fisx** [comment]
@rittermo this report explicitly contains the position "the three-color bar would be better here", which is further evidence that i'm on the side of our client re. https://github.com/liqd/aula/issues/506#issuecomment-219975820  (-:

**Comment by fisx** [comment]
I understand the request as follows:

- the vote count only counts positive votes, but should count the number of people who cared to cast a vote, which makes sense to me.  even better: we should show "n votes for; m votes against".
- the vote bar should be the same as in the idea detail view.  it should use the same widget, not copy the code, since the code may change in the future and we want to keep the two places in sync

Again, see also: #506.
