### ISSUE TITLE
Add icon for ideas that have reached the quorum

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#519]
If an idea has reached the quorum, a table icon should appear with the label “kann auf den Tisch” on the idea item in topic overview and the idea detail page. (see here https://marvelapp.com/ehhb43#10108424 for topic overview and here https://marvelapp.com/ehhb43#10108433 idea detail page)
A div is already rendered by Haskell.

**Comment by localgrr** [comment]
How do I get here ?

**Comment by fisx** [comment]
topic overview (idea lists) is fixed in #510; but idea detail view is not done.

reproduce:
- log in as admin
- go to prozessverwaltung; set both quorums to 1
- browse wild ideas in space "Schule".  click on any of the ideas.  that's your first sample page.
- logout; login as a moderator
- browse wild ideas in space "Schule".  click on any of the ideas.  that's your first sample page.

the code to be fixed:
https://github.com/liqd/aula/blob/8761ad8804903a868bb6a786f36c6c300d2c691e/src/Frontend/Page/Idea.hs#L218

it should look like this:
https://github.com/liqd/aula/blob/dc928ba71a1aaacc93929b68c45e1faa6a9a863b/src/Frontend/Fragment/IdeaList.hs#L104

**Comment by fisx** [comment]
also:

https://github.com/liqd/aula/blob/933e21ca59fa65c6c431d07956d4ca4328e0ecfe/src/Frontend/Fragment/VotesBar.hs#L57

**Comment by localgrr** [comment]
@fisx @rittermo on the click dummy there is this table icon, but in the actual page it's a CTA button. Should the table when you click it open the form ? I'm unclear about functionality here

**Comment by fisx** [comment]
everybody should see a table, but the functionality is different from role to role: moderators should be able to click it and reach the form, everybody else should not find anything clickable.

**Comment by localgrr** [comment]
![screenshot-localhost 8080 2016-05-23 15-17-58](https://cloud.githubusercontent.com/assets/701632/15472085/9e7cff9c-20f9-11e6-88f2-f28cfdfb6630.png) Link appearing when logged in as student
