### ISSUE TITLE
User avatar looks blurry

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#598]
The generated thumbnail of an uploaded avatar pic looks very blurry and low-res and is not round (this can probably be done via CSS). See https://aula-stage.liqd.net/user/18/ideas for an example.

**Comment by fisx** [comment]
@rittermo note that links into the staging server are only valid until we restart the server.  screenshots would be better evidence for issues.

**Comment by fisx** [comment]
related #602, #436

**Comment by fisx** [comment]
related: #601

**Comment by andorp** [comment]
The current resolution of the avatar pictures is 53x53 pixels, probably scaling up and and css could resolve this issue.

**Comment by fisx** [comment]
ideally, the image upload would write two images to disk, one -small.png and one -large.png (i don't care about the image format, but i think since we need to generate the rescaled versions anyway we might as well always choose the same).

one is 300px wide, the other 100px (configurable with source code constants).  both are round, and the corners outside the square are transparent.

i think we only anywhere need round avatars, and it would be most convenient, especially for the network browser, if we didn't have to adjust for that when rendering.
