### ISSUE TITLE
Authorization missing on post requests

### ISSUE THREAD

**Issue by np** [liqd/aula#646]
While all the endpoints with a frame are covered by our authorization system this is not the case for post-only endpoint AND the backend/api endpoints.

**Comment by fisx** [comment]
oops...

**Comment by fisx** [comment]
we should do two things (thanks @np)

1. take all end-points whose type ends with Post, and make them return token instead of `()`.  the token type could have a type class with auth checks.  do something similar for rest api.
1. iterate over the api types and verify that the entire app is verified.  this way if somebody adds an un-authorized end-point, they get a type error.

**Comment by fisx** [comment]
@np this is done, right?  i'll close this, please re-open if i'm missing anything.
