### ISSUE TITLE
Class-wide delegations for multiple classes

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#651]
Now that we have multiple classes per student, the button to delegate class-wide needed to be adapted. Nadine made two designs. I favor the second one with the dropdown as the first one with the overlay would mean we have a separate page.

![8 1 user profile delegate vote_stufe](https://cloud.githubusercontent.com/assets/15341015/16006975/27798b22-3170-11e6-99f2-15c5aa789f60.jpg)
![8 1 user profile delegate_02](https://cloud.githubusercontent.com/assets/15341015/16006976/27a42ad0-3170-11e6-9fcd-3dec5bf33b8b.jpg)

**Comment by fisx** [comment]
Fixed in #699.  Well, I claim it is fixed..  (-:

I've made a third design, consisting of a list of toggle buttons where the buttons originally were.  I agree Nadine's designs are nicer, but I suggest to take the short-cut and just tweak the css of what we have.

@rittermo: If you disagree, please re-open, and ideally move to it.3.
