### ISSUE TITLE
Delegations can not be withdrawn in class and school level.

### ISSUE THREAD

**Issue by andorp** [liqd/aula#737]
__Steps to reproduce:__
(1.) Log in with a user
(2.) Open another user's profile from the same class
(3.) Delegate your vote on school and class level to the other user
(4.) Withdraw delegation on school and class level

__Observed behavior:__
(4.) The delegations are not taken back

__Expected behavior:__
(4.) The delegations should have been taken back

**Comment by fisx** [comment]
ok, it appears you were right, and we should have fixed your TODO earlier instead of turning it into a FIXME.

...  but how?!  it looks like we are now deleting strictly fewer edges, but the problem was that either not enough edges were deleted, or they were, but something went wrong between state and UI.

what is my mistake?

**Comment by andorp** [comment]
https://github.com/liqd/aula/pull/743/files#diff-1db9ffe464f4032fd9d0959ff8078122L572

The delegate and delegatee was swapped there.
