### ISSUE TITLE
Problems with delegation power count?

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#782]
Maybe you could look at this, @fisx, and spare me an error-prone translation?

Abstimmung https://aula-stage1.liqd.net/space/2016-12c/topic/162/idea/347/view

Ich habe mit denwhc für eine Idee gestimmt, und die Idee hatte sofort 28 Dafür-Stimmen. 
Laut "Beauftragungsnetzwerk"-Grafik hat denwhc für dieses Thema 5 Stimmen. 
Bei einer Abstimmung über einen Verbesserungsvorschlag hatte er genau 1 Stimme. 
Könnt ihr das nochmal prüfen?

**Comment by fisx** [comment]
- the network shows only delegations on one scope, not the inherited edges from the more global scopes.  see #692.
- votes on comments (verbesserungsvorschlaege) do not take delegation into account.  this would be a bigger change request (>4h, needs estimate).
- likes can take delegations into account since #749.  there is a switch in the config file to turn that off.
-

**Comment by rittermo** [comment]
1) dashed implicit delegation edges, please
2) nope. talk client out of it.
3) great!

**Comment by fisx** [comment]
Fixed in #794, #797, #799.
