### ISSUE TITLE
Could not find module ‘Paths_aula’

### ISSUE THREAD

**Issue by lwm** [liqd/aula#945]
Coming to the final step after the [Getting Started with Docker](https://github.com/liqd/aula#getting-started-with-docker) section, I got the following error:

```
root@f845c1d5515b:/liqd/aula# make aula-server 
`test -d .stack-work/ && echo "stack exec --" || echo "cabal exec --"` runhaskell -j5 -isrc -itests -iexec -idist/build/autogen ./exec/Aula.hs

src/Config.hs:72:18:
    Could not find module ‘Paths_aula’
    it is a hidden module in the package ‘aula-0.24.4@aula_Bw0IDGj4DsfJC1QtgFP2Co’
    Use -v to see a list of the files searched for.
make: *** [aula-server] Error 1
```

**Comment by fisx** [comment]
thanks for reporting this.

i think the issue is that `stack install` does not keep the build artifacts under `./dist` where `runhaskell` is looking for them.  so you can try any of these two things:

1. call the `$HOME/.local/bin/aula-server` executable instead of `make aula-server`
1. run `stack build ...` instead of (or after) the `stack install ...` from the instructions.

let me know if that works and i'll fix the README.  of course another PR would be appreciated as well.  (-:
